[fix] more tests before changing grub config

diff --git a/bin/kernelupdate b/bin/kernelupdate
--- a/bin/kernelupdate
+++ b/bin/kernelupdate
@@ -9,13 +9,24 @@
 ## root ..
 ## kernel ../kernel-currentversion
 menulst='/boot/grub/menu.lst'
+newkernelpath='arch/x86/boot/bzImage'
 
 if [ "$(whoami)" != 'root' ]; then
   echo "You have no permission to run $0 as non-root user."
   exit 1;
 fi
 
-newkernel=`file arch/x86/boot/bzImage | /bin/grep --perl-regexp --only-matching '(?<=version )[\d\.]*'`
+if [ ! -e $menulst ]; then
+  echo "$menulst is not readable"
+  exit 1;
+fi
+
+if [ ! -e $newkernelpath ]; then
+  echo "Cannot find a new kernel at ~/$newkernelpath"
+  exit 1;
+fi
+
+newkernel=`file $newkernelpath | /bin/grep --perl-regexp --only-matching '(?<=version )[\d\.]*'`
 #echo "newkernel: $newkernel"
 cp arch/x86/boot/bzImage /boot/kernel-$newkernel
 existingkernels=(`/bin/grep --perl-regexp --only-matching '(?<=kernel-)[\d\.]*' $menulst`)
